### ISSUE TITLE
Icepay + woocommerce  & wplm issue: after install ice pay, woo commerce not working

### ISSUE THREAD

**Issue by Erwin28** [ICEPAY/WooCommerce#4] opened 2017-05-01 10:09 UTC
Hi, hope someone can help me with this problem. We use Wp+woo commerce and have multi-language plugin installed WPLM (i say this because reading about issue online, this might be reason of issue). We use different payment provider now, but switch to Icepay, after i activate plugin i try to go to woo commerce settings to set up ice pay and get 505 error page. If i deactivate ice pay plugin. Then work again.

**Comment by tsygankov** [comment] 2017-05-01 12:37
Hi Erwin28,

505 error means that the server does not support the HTTP protocol version used in the request. 

Can you please specify version of Wordpress, WooCommerce, WPLM, PHP and your webserver (Apache/ Nginx/ IIS)?

**Comment by Erwin28** [comment] 2017-05-01 13:00
Hi tsygankov,

These are the versions installed:
WordPress 4.7.2
WC version: 3.0.4
**WPLM**
WPLM: 3.7.0.
WPLM string translation: 2.5.3
Translation management: 2.3.0
WPLM media: 2.2.0
Woo commerce multilingual: 4.1.2

**Server**
LAMP stack on Ubuntu 16.04  LTS, Apache, MySQL, PHP 7

**Comment by tsygankov** [comment] 2017-05-01 13:56
Thank you! We are trying to reproduce the issue on out test environment.

Can you please send the output of phpinfo() to modules@icepay.com? We will check if you have all required php7 extensions installed.

**Comment by tsygankov** [comment] 2017-05-02 14:12
Thank you for providing the detailed information.

ICEPAY Payment Module for WooCommerce uses SOAP protocol for communication with the payment gateway. It seems that the SOAP extension is not installed for PHP7 on your server.

Could you please run the following command to install the SOAP extension for PHP 7.0?

`sudo  apt-get install php7.0-soap`

Please let me know whether the problem persists.

**Comment by Erwin28** [comment] 2017-05-03 06:51
Hi Tsygankov,

We installed the extension, the problem however persits.

Please advice.

Met vriendelijke groet, 
Erwin Daniels






MassID
Toccatastraat 87
1312TL Almere
info@massid.nl <http://www.massid.nl/>
+31 (0) 6 11 000 616

**Comment by Stijn-bs** [comment] 2017-05-21 08:38
Hello, I would like to report the same issue. I am not sure if it has the same root cause. But we cannot get the icepay plugin to work with woocommerce and WPML. When i enable the icepay plugin the server runs out of memore, however this is more an indication of some error occuring (memory already increased to 256 MB). An update of the plugin would be much appreciated! 

Thanks!

**Comment by tsygankov** [comment] 2017-06-11 22:44
Hi @Erwin28 and @Stijn-bs 

The problem is fixed in the latest [version](https://github.com/ICEPAY/WooCommerce/releases/tag/2.3.8b).

The problem was caused by `loaded_woocommerce_payment_gateways` function that is a part of WCML extension. 

```
    function loaded_woocommerce_payment_gateways( $load_gateways ){
        foreach( $load_gateways as $key => $gateway ){
            $load_gateway = is_string( $gateway ) ? new $gateway() : $gateway;
            $this->payment_gateways_filters( $load_gateway );
            $load_gateways[ $key ] = $load_gateway;
        }
        return $load_gateways;
    } 
```
WCML was creating new instances of ICEPAY Payment Gateway recursively, so there was an infinite loop. 

Could you please test the latest version and provide your feedback?

Thank you!

**Comment by tsygankov** [comment] 2017-07-09 20:15
I’m closing this issue, I hope the problem is solved now.

**Closed by tsygankov** 2017-07-09 20:15 UTC
Labels: bug, help wanted
